{% set name = "mouseinfo" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/MouseInfo-{{ version }}.tar.gz
  sha256: 2c62fb8885062b8e520a3cce0a297c657adcc08c60952eb05bc8256ef6f7f6e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - rubicon-objc
    - python-xlib
    - pyperclip
    - pillow >=4.0.0

test:
  imports:
    - mouseinfo  # [not linux]
  commands:
    - xvfb-run --auto-servernum python -c "import mouseinfo"  &  # [linux]
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asweigart/mouseinfo
  summary: An application to display XY position and RGB color information for the pixel currently under the mouse.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
